### ISSUE TITLE
Set Pin Screen

### ISSUE THREAD

**Issue by praveshkhatana** [Meshbits/pirate-wallet-layouts#21]
![IMG_8600](https://user-images.githubusercontent.com/26607301/135558985-295a879b-5e15-428e-92a7-c6c90bdb6efd.PNG)

This screen requires lots of fixes.
- In Top Nav: The back button is missing. 
- 'Change PIN' must be a part of the Nav-bar. Also, reduce the size as per design
- Instead of the 'Change PIN' text, I think only 'PIN' is sufficient on this screen because it's the first time for a user to set up a new PIN.
- Avoid using ALL CAPS in the title. Fix 'Set' text
- Move Entire middle content (including 'Set PIN' title, to the top. 
- Fix font color & size, specially in sub-title & supportive text.
- Keypad: Margin in-between buttons is too much. Try to keep it within a range of **user's thumb**
- keypad: The button size is smaller & the text isn't in the center.
- keypad: Back icon isn't correct. We are using Line-icons and it's a filled one.
- Progress bar/Circles: Both, filled & empty, aren't in the same size and are not Vertically align.

**Comment by lastw0nd3r** [comment]
In Top Nav: The back button is missing. - Fixed

**Comment by lastw0nd3r** [comment]
Quick update - I'm going to restructure the UI elements on this in the morning.

**Comment by lastw0nd3r** [comment]
Fixed:

- 'Change PIN' must be a part of the Nav-bar. Also, reduce the size as per design
- In Top Nav: The back button is missing.
- Instead of the 'Change PIN' text, I think only 'PIN' is sufficient on this screen because it's the first time for a user to set up a new PIN.
- Avoid using ALL CAPS in the title. Fix 'Set' text
- Move Entire middle content (including 'Set PIN' title, to the top.
- Fix font color & size, specially in sub-title & supportive text.
- keypad - fixed text isn't in center


Kindly note: 
- keypad: Back icon isn't correct. We are using Line-icons and it's a filled one. - Actually i am using SF Symbols - so, here i was using a filled one, just replaced it with an empty one.
- Progress bar/Circles: Both, filled & empty, aren't in the same size and are not Vertically align. - Actually, i am using the icons i have exported through figma for filled state and non-filled state of circles.

**Comment by lastw0nd3r** [comment]
Reduced the gap and button sizes on change pin flow

**Comment by praveshkhatana** [comment]
- Header Title isn't in the center
- Fix Back Icon and Verticle align button with title
- Increase Keypad button size and align text in the center(vertically & horizontally). Reduce the margin in between the keypad button and utilize that space for size.


> Progress bar/Circles: Both, filled & empty, aren't in the same size and are not Vertically align. - Actually, i am using the icons i have exported through figma for filled state and non-filled state of circles.

Let me check and verify it in Figma. I Will share the correct one soon

**Comment by praveshkhatana** [comment]
- Revert 'PIN' title back to default one 'Set PIN'

![IMG_F2E90E3906E9-1](https://user-images.githubusercontent.com/26607301/137005617-27292646-5f61-4833-a61e-d5e13340638e.jpeg)

**Comment by praveshkhatana** [comment]
- 'PIN SET SUCCESSFULLY' Popup is missing

**Comment by lastw0nd3r** [comment]
I have added a toast for this purpose, to skip bottom dialog - that will appear and dismiss within milliseconds.

**Comment by praveshkhatana** [comment]
> I have added a toast for this purpose, to skip bottom dialog - that will appear and dismiss within milliseconds.

Can we increase the time? it actually enhances the user experience.

**Comment by lastw0nd3r** [comment]
I agree, should I keep the toast and just increase the time? That should be it?

**Comment by praveshkhatana** [comment]
> I agree, should I keep the toast and just increase the time? That should be it?

perfect

**Comment by lastw0nd3r** [comment]
Done with changes. Thank you
